<?php
require_once __DIR__ . '/../app/auth.php';
require_once __DIR__ . '/../app/helpers.php';
$user = require_login();
$profile = ensure_student_profile((int)$user['id']);
$days = [
 ['Monday','MUN-dei','Lunes'],['Tuesday','TIUZ-dei','Martes'],['Wednesday','WENZ-dei','Miércoles'],
 ['Thursday','ZERS-dei','Jueves'],['Friday','FRAI-dei','Viernes'],['Saturday','SA-ter-dei','Sábado'],['Sunday','SAN-dei','Domingo']
];
function english_number(int $n): string {
 $ones=[0=>'zero',1=>'one',2=>'two',3=>'three',4=>'four',5=>'five',6=>'six',7=>'seven',8=>'eight',9=>'nine',10=>'ten',11=>'eleven',12=>'twelve',13=>'thirteen',14=>'fourteen',15=>'fifteen',16=>'sixteen',17=>'seventeen',18=>'eighteen',19=>'nineteen'];
 $tens=[2=>'twenty',3=>'thirty',4=>'forty',5=>'fifty',6=>'sixty',7=>'seventy',8=>'eighty',9=>'ninety'];
 if($n<20)return $ones[$n]; if($n<100){$t=intdiv($n,10);$u=$n%10;return $tens[$t].($u?'-'.$ones[$u]:'');} return 'one hundred';
}
$numbers=[]; for($i=1;$i<=100;$i++)$numbers[$i]=english_number($i);
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Inglés · Academia Star</title><link rel="stylesheet" href="assets/nuevo_curso/app.css?v=620english"><style>
:root{--purple:#7354e8;--ink:#28253c;--muted:#77748b}.eng-wrap{max-width:1120px;margin:auto;padding:22px}.eng-hero{padding:28px;border-radius:25px;color:white;background:linear-gradient(130deg,#4d42c9,#a45ee8);display:flex;justify-content:space-between;gap:18px;align-items:center}.eng-hero h2{margin:6px 0;font-size:30px}.eng-hero p{margin:0;max-width:650px}.eng-tabs{display:flex;gap:9px;flex-wrap:wrap;margin:20px 0}.eng-tabs button,.eng-btn{border:0;border-radius:12px;padding:11px 15px;font-weight:800;cursor:pointer;background:#f0edff;color:#4c3db0}.eng-tabs button.active,.eng-btn.primary{background:var(--purple);color:white}.eng-panel{background:#fff;border:1px solid #ebe8f5;border-radius:22px;padding:22px;margin:15px 0;box-shadow:0 12px 30px #33266b0d}.eng-panel h3{margin-top:0}.day-grid,.num-grid,.choice-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(135px,1fr));gap:10px}.flash{background:#f7f5ff;border-radius:15px;padding:15px;text-align:center}.flash strong{display:block;font-size:19px;color:#4938ad}.flash small{display:block;color:var(--muted);margin:6px}.num-grid button{border:1px solid #e9e5f7;background:#faf9ff;border-radius:12px;padding:11px;cursor:pointer;color:var(--ink)}.num-grid button b{display:block;color:var(--purple);font-size:18px}.exercise{background:#f8f7ff;padding:18px;border-radius:16px;margin-top:14px}.exercise input{padding:12px;border:1px solid #dcd6f1;border-radius:10px;font-size:16px;max-width:100%;box-sizing:border-box}.feedback{font-weight:800;min-height:25px;margin-top:10px}.eng-section{display:none}.eng-section.active{display:block}.choice-grid button{border:1px solid #e5e0f4;background:#fff;border-radius:12px;padding:12px;cursor:pointer}.choice-grid button:hover{border-color:var(--purple)}.small-note{color:var(--muted);font-size:13px}.progress-line{height:8px;background:#eeeafa;border-radius:9px;overflow:hidden}.progress-line span{display:block;height:100%;width:0;background:#7354e8}@media(max-width:700px){.eng-wrap{padding:12px}.eng-hero{padding:22px}.eng-hero h2{font-size:25px}}
</style></head><body><div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">L</div><div><strong>Academia</strong><span>Nuevo curso</span></div></div><nav><a class="nav-btn" href="nuevo_curso.php"><span>🏠</span> Inicio</a><a class="nav-btn" href="asignatura.php?subject=lengua"><span>📖</span> Lengua</a><a class="nav-btn" href="asignatura.php?subject=matematicas"><span>🔢</span> Matemáticas</a><a class="nav-btn active" href="ingles.php"><span>🇬🇧</span> Inglés</a><a class="nav-btn" href="tasks.php"><span>📝</span> Tareas</a><a class="nav-btn" href="profile.php"><span>👧</span> Perfil</a></nav><a class="parent-btn" href="nuevo_curso.php">⌂ Nuevo curso</a></aside><main class="main"><div class="eng-wrap"><header class="topbar"><div class="greeting"><span class="eyebrow">CURSO 2026/27 · EXAMEN</span><h1>🇬🇧 Inglés</h1></div><div class="stats-mini"><span>⭐ <b><?= (int)$profile['xp'] ?></b></span></div></header>
<section class="eng-hero"><div><span>PREPARACIÓN DEL EXAMEN</span><h2>Days of the week & Numbers</h2><p>Aprende a reconocerlos, escribirlos y decirlos en voz alta. Practica un poco cada día.</p></div><div style="font-size:62px">🗣️</div></section>
<div class="eng-tabs" role="tablist"><button class="active" data-tab="learn">📚 Estudiar</button><button data-tab="days">📅 Días</button><button data-tab="numbers">🔢 Números</button><button data-tab="bootcamp">💪 Memorizar 1–22</button><button data-tab="write">✍️ Escribir</button><button data-tab="speak">🔊 Oral</button><button data-tab="test">🎯 Examen</button></div>
<section class="eng-section active" id="learn"><div class="eng-panel"><h3>Plan de estudio</h3><div class="day-grid"><div class="flash"><strong>1. Aprende</strong><small>Lee cada palabra y escucha su pronunciación.</small></div><div class="flash"><strong>2. Memoriza</strong><small>Tapa la respuesta e intenta recordarla.</small></div><div class="flash"><strong>3. Escribe</strong><small>Escribe la palabra sin copiarla.</small></div><div class="flash"><strong>4. Di en voz alta</strong><small>Repite y comprueba cómo suena.</small></div></div></div><div class="eng-panel"><h3>Reglas que ayudan</h3><ul><li>Los días de la semana empiezan con mayúscula en inglés: <b>Monday</b>, <b>Tuesday</b>…</li><li>Del 13 al 19 suelen terminar en <b>-teen</b>: thirteen, fourteen, fifteen…</li><li>Las decenas terminan en <b>-ty</b>: twenty, thirty, forty, fifty…</li><li>Entre 21 y 99 se usa guion al escribirlos: <b>twenty-one</b>, <b>forty-six</b>.</li><li>100 se escribe <b>one hundred</b>.</li></ul><button class="eng-btn primary" onclick="showTab('days')">Empezar por los días →</button></div></section>
<section class="eng-section" id="days"><div class="eng-panel"><h3>Los 7 días de la semana</h3><p>Escucha cada palabra y repítela. La pronunciación escrita es una ayuda aproximada, no una transcripción exacta.</p><div class="day-grid"><?php foreach($days as $d): ?><div class="flash"><strong><?= htmlspecialchars($d[0]) ?></strong><small><?= htmlspecialchars($d[2]) ?></small><small>Suena parecido a: <?= htmlspecialchars($d[1]) ?></small><button class="eng-btn" onclick="say(<?= json_encode($d[0]) ?>)">🔊 Escuchar</button></div><?php endforeach; ?></div><div class="exercise"><h4>¿Qué día viene después de…?</h4><p id="dayQuestion"></p><div class="choice-grid" id="dayChoices"></div><div class="feedback" id="dayFeedback"></div><button class="eng-btn" onclick="newDayQuestion()">Otra pregunta</button></div></div></section>
<section class="eng-section" id="numbers"><div class="eng-panel"><h3>Números del 1 al 100</h3><p>Busca un número para ver cómo se escribe y escucha cómo se pronuncia. Estudia primero del 1 al 20, después las decenas y por último los demás.</p><div style="display:flex;gap:8px;flex-wrap:wrap;margin:14px 0"><label for="range">Bloque:</label><select id="range" onchange="renderNumbers()"><option value="1-20">1–20</option><option value="21-40">21–40</option><option value="41-60">41–60</option><option value="61-80">61–80</option><option value="81-100">81–100</option><option value="1-100">Todos (1–100)</option></select></div><div class="num-grid" id="numGrid"></div></div></section>
<section class="eng-section" id="bootcamp"><div class="eng-panel"><h3>💪 Entrenamiento intensivo: números del 1 al 22</h3><p>Este bloque insiste especialmente en los números del 1 al 22. Tendrás preguntas nuevas continuamente: escribir palabras, reconocer cifras, completar letras, escuchar y elegir la respuesta correcta.</p><div class="day-grid"><div class="flash"><strong>1–12</strong><small>Memoriza cada palabra porque muchas no siguen una regla sencilla.</small></div><div class="flash"><strong>13–19</strong><small>Fíjate en la terminación <b>-teen</b>.</small></div><div class="flash"><strong>20, 21, 22</strong><small>Twenty, twenty-one, twenty-two.</small></div></div><div class="progress-line"><span id="bootProgress"></span></div><p id="bootStats"><b>Racha:</b> 0 · <b>Correctas:</b> 0 · <b>Preguntas:</b> 0</p><div class="exercise"><p class="small-note" id="bootType">Pregunta de escritura</p><h3 id="bootPrompt" style="font-size:24px;line-height:1.35">Pulsa «Empezar práctica»</h3><div id="bootChoices" class="choice-grid"></div><div id="bootInputArea" style="display:none;margin-top:12px"><input id="bootAnswer" autocomplete="off" placeholder="Escribe la respuesta" style="width:min(100%,360px)"><button class="eng-btn primary" onclick="checkBootInput()">Comprobar</button></div><div class="feedback" id="bootFeedback" aria-live="polite"></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px"><button class="eng-btn primary" id="bootStart" onclick="startBootcamp()">▶ Empezar práctica</button><button class="eng-btn" id="bootNext" onclick="nextBootQuestion()" disabled>Siguiente pregunta →</button><button class="eng-btn" onclick="sayBootAnswer()">🔊 Escuchar respuesta</button></div><p class="small-note">La práctica da más peso a los números que suelen confundirse, y vuelve a preguntar los fallados. Intenta escribir sin mirar la tabla.</p></div></div><div class="eng-panel"><h3>Tabla para memorizar del 1 al 22</h3><div class="num-grid" id="bootStudyGrid"></div></div></section>
<section class="eng-section" id="write"><div class="eng-panel"><h3>Entrena la escritura</h3><p>Escribe en inglés la palabra que corresponde al número o al día. No mires la tabla mientras respondes.</p><div class="exercise"><p id="writePrompt"></p><input id="writeAnswer" autocomplete="off" placeholder="Escribe la respuesta en inglés"><button class="eng-btn primary" onclick="checkWrite()">Comprobar</button><button class="eng-btn" onclick="sayCurrentPrompt()">🔊 Escuchar pista</button><div class="feedback" id="writeFeedback"></div><button class="eng-btn" onclick="newWriteQuestion()">Siguiente</button></div></div></section>
<section class="eng-section" id="speak"><div class="eng-panel"><h3>Práctica oral</h3><p>Escucha la palabra, repítela en voz alta y pulsa «He repetido». Si el navegador permite reconocimiento de voz en inglés, también puedes comprobar lo que has dicho.</p><div class="exercise"><p id="speakPrompt" style="font-size:26px;font-weight:900"></p><button class="eng-btn primary" onclick="sayCurrentSpeak()">🔊 Escuchar pronunciación</button> <button class="eng-btn" onclick="listenSpeak()">🎙️ Comprobar mi voz</button> <button class="eng-btn" onclick="newSpeakQuestion()">Otra palabra</button><div class="feedback" id="speakFeedback"></div><p class="small-note">La comprobación por micrófono depende del navegador y de los permisos del dispositivo. Si no está disponible, escucha y repite en voz alta.</p></div></div></section>
<section class="eng-section" id="test"><div class="eng-panel"><h3>Examen de inglés · 30 preguntas</h3><p>15 preguntas tipo test y 15 de escritura. En las de escritura se aceptan los guiones opcionales y los espacios equivalentes: por ejemplo, <b>twenty-one</b>, <b>twenty one</b> y <b>twentyone</b> se consideran correctos.</p><div class="progress-line"><span id="testProgress"></span></div><div class="exercise"><p id="testPrompt"></p><div id="testOptions" class="choice-grid"></div><div class="feedback" id="testFeedback"></div><button class="eng-btn primary" id="testNext" onclick="nextTest()" disabled>Continuar</button><div id="testResult"></div></div></div></section>
<p class="small-note"><a href="nuevo_curso.php">← Volver al curso</a></p></div></main></div>
<script>
const days=[{en:'Monday',es:'lunes'},{en:'Tuesday',es:'martes'},{en:'Wednesday',es:'miércoles'},{en:'Thursday',es:'jueves'},{en:'Friday',es:'viernes'},{en:'Saturday',es:'sábado'},{en:'Sunday',es:'domingo'}];
const nums={<?php $parts=[];foreach($numbers as $n=>$word)$parts[]=$n.':'.json_encode($word);echo implode(',',$parts); ?>};
function showTab(id){document.querySelectorAll('.eng-section').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));if(id==='numbers')renderNumbers();if(id==='bootcamp')renderBootStudy();if(id==='write')newWriteQuestion();if(id==='speak')newSpeakQuestion();if(id==='test'&&!testStarted)startTest();}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));
function say(t){if(!('speechSynthesis'in window)){alert('La voz no está disponible en este navegador.');return}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='en-GB';u.rate=.82;speechSynthesis.speak(u)}
function renderNumbers(){let [a,b]=document.getElementById('range').value.split('-').map(Number);let el=document.getElementById('numGrid');el.innerHTML='';for(let i=a;i<=b;i++){let btn=document.createElement('button');btn.innerHTML='<b>'+i+'</b>'+nums[i];btn.onclick=()=>say(nums[i]);el.appendChild(btn)}}
let dayAnswer=0;function newDayQuestion(){dayAnswer=Math.floor(Math.random()*7);let d=days[dayAnswer];document.getElementById('dayQuestion').textContent='¿Qué día viene después de '+d.en+'?';let correct=days[(dayAnswer+1)%7].en;let opts=[correct];while(opts.length<4){let v=days[Math.floor(Math.random()*7)].en;if(!opts.includes(v))opts.push(v)}opts.sort(()=>Math.random()-.5);let box=document.getElementById('dayChoices');box.innerHTML='';opts.forEach(v=>{let b=document.createElement('button');b.textContent=v;b.onclick=()=>{document.getElementById('dayFeedback').textContent=v===correct?'¡Correcto! '+correct+' significa '+days[(dayAnswer+1)%7].es+'.':'Casi. La respuesta correcta es '+correct+'.'};box.appendChild(b)});document.getElementById('dayFeedback').textContent=''}
let currentWrite='';function newWriteQuestion(){let useDay=Math.random()<.25;currentWrite=useDay?days[Math.floor(Math.random()*7)].en:nums[1+Math.floor(Math.random()*100)];document.getElementById('writePrompt').textContent=useDay?'Escribe en inglés el día: '+days.find(d=>d.en===currentWrite).es:'Escribe en letras el número: '+Object.keys(nums).find(k=>nums[k]===currentWrite);document.getElementById('writeAnswer').value='';document.getElementById('writeFeedback').textContent=''}function checkWrite(){let val=document.getElementById('writeAnswer').value.trim().toLowerCase().replace(/[’']/g,"'").replace(/\s+/g,' ');let correct=currentWrite.toLowerCase();document.getElementById('writeFeedback').textContent=val===correct?'¡Muy bien! Está bien escrito.':'Aún no. La respuesta correcta es: '+currentWrite; if(val===correct) say('Correct! '+currentWrite)}function sayCurrentPrompt(){say(currentWrite)}
const bootNums=Array.from({length:22},(_,i)=>i+1);let bootCurrent=1,bootMode='write',bootCorrect=0,bootAsked=0,bootStreak=0,bootAnswered=false,bootWrong=[],bootStarted=false;
function renderBootStudy(){const box=document.getElementById('bootStudyGrid');if(!box||box.children.length)return;bootNums.forEach(n=>{const b=document.createElement('button');b.innerHTML='<b>'+n+'</b>'+nums[n];b.onclick=()=>say(nums[n]);box.appendChild(b)})}
function startBootcamp(){bootCorrect=0;bootAsked=0;bootStreak=0;bootWrong=[];bootStarted=true;document.getElementById('bootStart').textContent='↻ Reiniciar práctica';nextBootQuestion()}
function pickBootNumber(){// Favorece 1–22; los errores vuelven a salir pronto.
 if(bootWrong.length&&Math.random()<.38)return bootWrong[Math.floor(Math.random()*bootWrong.length)];return bootNums[Math.floor(Math.random()*bootNums.length)]}
function nextBootQuestion(){if(!bootStarted){startBootcamp();return}bootCurrent=pickBootNumber();bootAsked++;bootAnswered=false;document.getElementById('bootNext').disabled=true;document.getElementById('bootFeedback').textContent='';document.getElementById('bootChoices').innerHTML='';document.getElementById('bootInputArea').style.display='none';document.getElementById('bootAnswer').value='';const type=Math.floor(Math.random()*5);let prompt='';if(type===0||type===1){bootMode='write';prompt='Escribe en inglés el número '+bootCurrent+'.';document.getElementById('bootInputArea').style.display='block';document.getElementById('bootAnswer').placeholder='Escribe: '+(bootCurrent>=13&&bootCurrent<=19?'terminación -teen si corresponde':'la palabra en inglés');document.getElementById('bootAnswer').focus()}else if(type===2){bootMode='digit';prompt='¿Qué cifra corresponde a “'+nums[bootCurrent]+'”?';showBootChoices(String(bootCurrent),bootNums.map(n=>String(n)))}else if(type===3){bootMode='missing';let word=nums[bootCurrent];let ix=word.length>2?1+Math.floor(Math.random()*(word.length-1)):0;window.bootExpected=word;window.bootMask=word.slice(0,ix)+'_'.repeat(Math.min(2,word.length-ix));prompt='Completa la palabra del número '+bootCurrent+':  '+window.bootMask;document.getElementById('bootInputArea').style.display='block';document.getElementById('bootAnswer').placeholder='Escribe la palabra completa'}else{bootMode='choice';prompt='Elige cómo se escribe el número '+bootCurrent+'.';showBootChoices(nums[bootCurrent],bootNums.map(n=>nums[n]))}document.getElementById('bootType').textContent='Pregunta '+bootAsked+' · '+(['Escritura','Escritura','Reconocer cifra','Completar letras','Elegir palabra'][type]);document.getElementById('bootPrompt').textContent=prompt;document.getElementById('bootStats').innerHTML='<b>Racha:</b> '+bootStreak+' · <b>Correctas:</b> '+bootCorrect+' · <b>Preguntas:</b> '+bootAsked;document.getElementById('bootProgress').style.width=(bootAsked%20)*5+'%'}
function showBootChoices(correct,all){let opts=[correct];let pool=all.filter(v=>v!==correct);while(opts.length<4&&pool.length){const i=Math.floor(Math.random()*pool.length);opts.push(pool.splice(i,1)[0])}opts.sort(()=>Math.random()-.5);const box=document.getElementById('bootChoices');opts.forEach(v=>{const b=document.createElement('button');b.textContent=v;b.onclick=()=>answerBoot(v===correct,v);box.appendChild(b)})}
function checkBootInput(){if(bootAnswered)return;const val=document.getElementById('bootAnswer').value.trim().toLowerCase().replace(/[’']/g,"'").replace(/\s+/g,' ').replace(/-/g,'');const correct=nums[bootCurrent].toLowerCase().replace(/-/g,'');answerBoot(val===correct,val)}
function answerBoot(ok,given){if(bootAnswered)return;bootAnswered=true;const correct=nums[bootCurrent];if(ok){bootCorrect++;bootStreak++;bootWrong=bootWrong.filter(n=>n!==bootCurrent);document.getElementById('bootFeedback').textContent='¡Correcto! '+bootCurrent+' se escribe '+correct+'.';}else{bootStreak=0;if(!bootWrong.includes(bootCurrent))bootWrong.push(bootCurrent);document.getElementById('bootFeedback').textContent='Vamos a memorizarlo: '+bootCurrent+' se escribe “'+correct+'”.';}document.getElementById('bootNext').disabled=false;document.getElementById('bootStats').innerHTML='<b>Racha:</b> '+bootStreak+' · <b>Correctas:</b> '+bootCorrect+' · <b>Preguntas:</b> '+bootAsked;document.getElementById('bootChoices').querySelectorAll('button').forEach(b=>b.disabled=true);if(!ok&&bootMode==='write')say(correct)}
function sayBootAnswer(){say(nums[bootCurrent])}
let currentSpeak='';function newSpeakQuestion(){currentSpeak=Math.random()<.2?days[Math.floor(Math.random()*7)].en:nums[1+Math.floor(Math.random()*100)];document.getElementById('speakPrompt').textContent=currentSpeak;document.getElementById('speakFeedback').textContent='Escucha y repite en voz alta.'}function sayCurrentSpeak(){say(currentSpeak)}function listenSpeak(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){document.getElementById('speakFeedback').textContent='Este navegador no ofrece reconocimiento de voz. Escucha y repite en voz alta.';return}let rec=new SR();rec.lang='en-GB';rec.onresult=e=>{let got=e.results[0][0].transcript.toLowerCase().trim();document.getElementById('speakFeedback').textContent='He entendido: “'+got+'”. '+(got.replace(/[^a-z ]/g,'').trim()===currentSpeak.toLowerCase()?'¡Coincide!':'Vuelve a escuchar y prueba otra vez.');};rec.onerror=()=>document.getElementById('speakFeedback').textContent='No he podido oírte. Comprueba el permiso del micrófono o repite en voz alta.';rec.start()}
let test=[],testIndex=0,testScore=0,testStarted=false,testAnswered=false;
function normalizeEnglishAnswer(value){return String(value||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’']/g,'').replace(/[^a-z0-9]/g,'')}
function startTest(){
 testStarted=true;testIndex=0;testScore=0;test=[];
 // 15 de elección múltiple, seguidas de 15 en las que debe escribir la respuesta.
 for(let i=0;i<30;i++){
  const writing=i>=15;
  if(Math.random()<.18){
   const d=days[Math.floor(Math.random()*days.length)];
   const item={kind:writing?'write':'choice',q:'¿Cómo se escribe “'+d.es+'” en inglés?',a:d.en,opts:[]};
   if(!writing)item.opts=shuffle([d.en,...days.filter(x=>x.en!==d.en).sort(()=>Math.random()-.5).slice(0,3).map(x=>x.en)]);
   test.push(item);
  }else{
   // Refuerzo centrado en 1–22, con algunos números hasta 100.
   const n=Math.random()<.82?1+Math.floor(Math.random()*22):1+Math.floor(Math.random()*100);
   const item={kind:writing?'write':'choice',q:'¿Cómo se escribe el número '+n+' en inglés?',a:nums[n],number:n,opts:[]};
   if(!writing){
    const pool=Object.keys(nums).map(Number).filter(x=>x!==n).sort(()=>Math.random()-.5).slice(0,3).map(x=>nums[x]);
    item.opts=shuffle([item.a,...pool]);
   }
   test.push(item);
  }
 }
 renderTest();
}
function shuffle(a){return a.sort(()=>Math.random()-.5)}
function renderTest(){
 testAnswered=false;let t=test[testIndex];
 document.getElementById('testPrompt').textContent='Pregunta '+(testIndex+1)+' de 30 · '+(testIndex<15?'Parte 1: elige la respuesta':'Parte 2: escribe la respuesta')+': '+t.q;
 document.getElementById('testProgress').style.width=(testIndex/30*100)+'%';
 document.getElementById('testFeedback').textContent='';document.getElementById('testNext').disabled=true;
 document.getElementById('testNext').textContent=testIndex===29?'Ver resultado':'Continuar';document.getElementById('testResult').textContent='';
 let box=document.getElementById('testOptions');box.innerHTML='';
 if(t.kind==='write'){
  const wrap=document.createElement('div');wrap.style.cssText='display:flex;gap:8px;flex-wrap:wrap;margin-top:10px';
  const input=document.createElement('input');input.id='testWrittenAnswer';input.autocomplete='off';input.placeholder='Escribe la palabra en inglés';input.setAttribute('aria-label','Respuesta escrita');input.style.cssText='padding:12px;border:1px solid #dcd6f1;border-radius:10px;font-size:16px;max-width:100%;flex:1;min-width:220px';
  const btn=document.createElement('button');btn.className='eng-btn primary';btn.textContent='Comprobar respuesta';btn.onclick=()=>checkWrittenTestAnswer();
  input.addEventListener('keydown',e=>{if(e.key==='Enter')checkWrittenTestAnswer()});wrap.append(input,btn);box.appendChild(wrap);setTimeout(()=>input.focus(),50);
 }else{
  t.opts.forEach(v=>{let b=document.createElement('button');b.textContent=v;b.onclick=()=>answerTest(v===t.a);box.appendChild(b)});
 }
}
function answerTest(ok){if(testAnswered)return;testAnswered=true;const t=test[testIndex];if(ok){testScore++;document.getElementById('testFeedback').textContent='¡Correcto!';}else document.getElementById('testFeedback').textContent='La respuesta correcta es: '+t.a+'.';document.getElementById('testOptions').querySelectorAll('button').forEach(x=>x.disabled=true);const input=document.getElementById('testWrittenAnswer');if(input)input.disabled=true;document.getElementById('testNext').disabled=false}
function checkWrittenTestAnswer(){if(testAnswered)return;const input=document.getElementById('testWrittenAnswer');const given=input?input.value:'';if(!given.trim()){document.getElementById('testFeedback').textContent='Escribe una respuesta antes de comprobar.';return}answerTest(normalizeEnglishAnswer(given)===normalizeEnglishAnswer(test[testIndex].a))}
function nextTest(){if(!testAnswered)return;if(testIndex<29){testIndex++;renderTest()}else{document.getElementById('testPrompt').textContent='Examen terminado';document.getElementById('testOptions').innerHTML='';document.getElementById('testProgress').style.width='100%';document.getElementById('testFeedback').textContent='Has acertado '+testScore+' de 30 ('+Math.round(testScore/30*100)+'%).';document.getElementById('testResult').innerHTML='<button class="eng-btn primary" onclick="startTest()">Repetir examen</button>';document.getElementById('testNext').disabled=true}}

newDayQuestion();renderNumbers();newWriteQuestion();newSpeakQuestion();
</script></body></html>
