<?php
require_once __DIR__ . '/../app/auth.php';
require_once __DIR__ . '/../app/helpers.php';
$user=require_login();
$profile=ensure_student_profile((int)$user['id']);
$topics=[
 ['title'=>'Multiplicar por 10, 100 y 1000','key'=>'multiplicar-por-10-100-1000','explain'=>'Cuando multiplicas por 10, 100 o 1000 puedes añadir uno, dos o tres ceros si el número es entero. Ejemplo: 34×100=3400.'],
 ['title'=>'Multiplicaciones de varias cifras','key'=>'multiplicaciones-varias-cifras','explain'=>'Descompón la multiplicación por decenas y unidades o colócala en vertical. Comprueba el resultado al final.'],
 ['title'=>'Propiedad distributiva','key'=>'propiedad-distributiva','explain'=>'Puedes descomponer un factor: 236×24 = 236×20 + 236×4. Después sumas los resultados.'],
 ['title'=>'Orden de las operaciones','key'=>'expresiones','explain'=>'Primero se resuelven los paréntesis. Después las multiplicaciones y divisiones. Al final, sumas y restas.'],
 ['title'=>'Potencias: base y exponente','key'=>'potencias-base-exponente','explain'=>'La base es el número que se repite. El exponente indica cuántas veces se multiplica. 5³ significa 5×5×5.'],
 ['title'=>'Cuadrados y cubos','key'=>'cuadrados-y-cubos','explain'=>'Exponente 2 = cuadrado. Exponente 3 = cubo. Por ejemplo, 7²=49 y 4³=64.'],
 ['title'=>'Problemas de multiplicación','key'=>'problemas-multiplicacion','explain'=>'Lee el problema, decide qué operación necesitas, calcula y comprueba si el resultado tiene sentido.'],
];
$db=db();$taskMap=[];
try{
 $q=$db->prepare("SELECT id,title,topic_key FROM study_tasks WHERE active=1 AND subject_key='matematicas'");$q->execute();
 foreach($q->fetchAll() as $r){$taskMap[$r['topic_key']][]=$r;}
}catch(Throwable $e){}
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#2f8fe5"><title>Matemáticas · Refuerzo · Academia Star</title><link rel="stylesheet" href="assets/nuevo_curso/app.css?v=625"><style>
:root{--blue:#2f8fe5;--violet:#7558e8;--ink:#25243a;--muted:#77758c;--line:#ebe8f5;--shadow:0 14px 35px rgba(45,35,95,.08)}.course-only .sidebar{display:flex}.course-only .main{margin-left:260px}.hero{background:linear-gradient(135deg,#236fc1,#7558e8);color:#fff;border-radius:28px;padding:30px;box-shadow:0 18px 40px rgba(45,60,160,.18);display:flex;justify-content:space-between;gap:20px;align-items:center}.hero h2{margin:7px 0;font-size:31px}.hero p{margin:0;max-width:760px;opacity:.93;line-height:1.5}.hero-icon{font-size:56px;background:rgba(255,255,255,.15);width:88px;height:88px;border-radius:25px;display:grid;place-items:center}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.big-btn{display:inline-flex;text-decoration:none;padding:13px 17px;border-radius:14px;font-weight:900;background:#fff;color:#3158b6}.big-btn.alt{background:rgba(255,255,255,.15);color:#fff;border:1px solid rgba(255,255,255,.3)}.section{margin-top:24px}.section h2{margin:0 0 7px}.section>p{color:var(--muted)}.explain-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px;margin-top:15px}.explain{background:#fff;border:1px solid var(--line);border-radius:21px;padding:19px;box-shadow:var(--shadow)}.explain h3{margin:0 0 7px;font-size:18px}.explain p{margin:0;color:var(--muted);line-height:1.55}.example{margin-top:11px;padding:11px 13px;border-radius:12px;background:#f3f7ff;color:#28558f;font-weight:800}.practice{margin-top:12px;display:flex;gap:7px;flex-wrap:wrap}.practice a{font-size:12px;font-weight:900;text-decoration:none;padding:8px 10px;border-radius:10px;background:#f3f1fa;color:#4a4560}.practice a.primary{background:#2f8fe5;color:#fff}.exam-card{margin-top:24px;background:#fff;border:1px solid var(--line);border-radius:24px;padding:22px;box-shadow:var(--shadow);display:flex;justify-content:space-between;gap:20px;align-items:center}.exam-card h2{margin:0}.exam-card p{color:var(--muted);margin:7px 0}.exam-btn{background:linear-gradient(135deg,#7558e8,#a15de8);color:#fff;text-decoration:none;padding:13px 17px;border-radius:14px;font-weight:900;white-space:nowrap}@media(max-width:760px){.course-only .main{margin-left:0}.course-only .sidebar{transform:translateX(-100%)}.course-only .sidebar.open{transform:translateX(0)}.explain-grid{grid-template-columns:1fr}.hero{padding:23px}.hero h2{font-size:26px}.hero-icon{display:none}.exam-card{align-items:flex-start;flex-direction:column}.exam-btn{width:100%;text-align:center}}
</style></head><body class="course-only"><div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">L</div><div><strong>Academia</strong><span>Nuevo curso</span></div></div><nav><a class="nav-btn" href="nuevo_curso.php"><span>🏠</span> Inicio</a><a class="nav-btn" href="asignatura.php?subject=lengua"><span>📖</span> Lengua</a><a class="nav-btn active" href="asignatura.php?subject=matematicas"><span>🔢</span> Matemáticas</a><a class="nav-btn" href="tasks.php"><span>📝</span> Tareas</a><a class="nav-btn" href="profile.php"><span>👧</span> Perfil</a></nav><a class="parent-btn" href="nuevo_curso.php">⌂ Nuevo curso</a><?php if(($user['role']??'')==='admin'): ?><a class="parent-btn" href="../admin/panel.php">🔒 Panel de Juanra</a><?php endif; ?></aside><main class="main"><header class="topbar"><button class="menu-btn" id="menuBtn" type="button">☰</button><div class="greeting"><span class="eyebrow">PREPARACIÓN PARA EL EXAMEN</span><h1>🔢 Matemáticas</h1></div><div class="stats-mini"><span>🔥 <b><?= (int)$profile['daily_streak'] ?></b></span><span>⭐ <b><?= (int)$profile['xp'] ?></b></span></div></header>
<section class="hero"><div><span class="eyebrow" style="color:#fff">ENTRENAMIENTO INTENSIVO</span><h2>Vamos a darle caña a Matemáticas</h2><p>Explicaciones cortas, muchos ejercicios, repetición y exámenes. La idea es que Leire no solo reconozca la respuesta: que sepa hacerla sola.</p><div class="actions"><a class="big-btn" href="matematicas_examen.php">📝 Examen general · 20 preguntas</a><a class="big-btn alt" href="asignatura.php?subject=matematicas">📚 Ver todos los temas</a></div></div><div class="hero-icon">🧠</div></section>
<section class="section"><h2>📖 Explicaciones que hay que dominar</h2><p>Lee cada explicación y después haz ejercicios. Si falla un concepto, vuelve a practicarlo antes del examen.</p><div class="explain-grid">
<?php foreach($topics as $t): ?><article class="explain"><h3><?= e($t['title']) ?></h3><p><?= e($t['explain']) ?></p><div class="practice"><?php foreach(($taskMap[$t['key']]??[]) as $task): ?><a class="primary" href="task_activity.php?task_id=<?= (int)$task['id'] ?>&mode=study">🧠 <?= e($task['title']) ?></a><?php endforeach; ?></div></article><?php endforeach; ?></div></section>
<section class="exam-card"><div><h2>🎯 Examen general</h2><p>20 preguntas sobre todo el bloque: multiplicaciones, distributiva, expresiones, potencias, cuadrados, cubos y problemas.</p><p><b>Cada intento genera una combinación distinta.</b></p></div><a class="exam-btn" href="matematicas_examen.php">Empezar examen →</a></section>
</main></div><script>const m=document.getElementById('menuBtn'),s=document.querySelector('.sidebar');if(m)m.onclick=()=>s.classList.toggle('open');</script></body></html>
