<?php
session_start();
require_once __DIR__ . '/../app/auth.php';
require_once __DIR__ . '/../app/helpers.php';
$user=require_login();$profile=ensure_student_profile((int)$user['id']);
function mc($prompt,$answer,$wrong){$opts=$wrong;$opts[]=$answer;shuffle($opts);return ['type'=>'mc','prompt'=>$prompt,'answer'=>$answer,'options'=>$opts];}
function wr($prompt,$answer,$explain='') { return ['type'=>'write','prompt'=>$prompt,'answer'=>(string)$answer,'explain'=>$explain]; }
function pool(){
 $p=[];
 $nums=[12,18,23,34,45,56,67,72,84,95,108,120,203,305,410,525,702,804];
 foreach($nums as $n){$p[]=mc("$n × 10 = ?",$n*10,[$n*10+10,$n*100,$n+10]);}
 foreach([20,30,40,50,60,70,80,90,200,300,400,500] as $n){$a=7*$n;$p[]=mc("7 × $n = ?",$a,[$a+70,$a*10,$a-70]);}
 foreach([[237,92],[156,56],[457,219],[529,842],[267,345],[328,47],[614,23],[703,18],[125,64],[432,35],[806,27],[219,48]] as [$a,$b]){$ans=$a*$b;$p[]=mc("$a × $b = ?",$ans,[$ans+100,$ans-100,$ans+1000]);}
 foreach([[236,24],[28,53],[832,74],[964,123],[513,42],[703,500],[405,32],[125,16]] as [$a,$b]){$ans=$a*$b;$p[]=mc("Usa la propiedad distributiva: $a × $b = ?",$ans,[$ans+10,$ans-10,$ans+100]);}
 $expr=[['5 × (10 − 7)',15],['(4 + 3) × 8',56],['12 + 6 × 2',24],['40 − 3 × 7',19],['(25 + 6) × 3',93],['30 × 40 + 7',1207],['(8 + 2) × 5',50],['50 − 4 × 6',26],['(12 − 5) × 9',63],['6 × 7 + 10',52]];
 foreach($expr as [$q,$a])$p[]=mc("Resuelve: $q",$a,[$a+6,$a-6,$a+10]);
 foreach([[2,3],[6,4],[5,2],[7,3],[3,4],[10,3],[9,2],[4,3],[12,2],[5,3]] as [$b,$e]){$ans=$b**$e;$p[]=mc("¿Cuánto vale $b^$e?",$ans,[$ans+$b,$ans-$b,$b*$e]);}
 foreach([[5,2],[7,2],[9,2],[12,2],[4,3],[3,3],[6,3],[10,3]] as [$b,$e]){$ans=$b**$e;$name=$e===2?'cuadrado':'cubo';$p[]=mc("$b^$e$ es un $name y vale…",$ans,[$ans+$b,$b*$e,$ans-$b]);}
 $probs=[['En 24 cajas hay 236 piezas en cada una. ¿Cuántas piezas hay?',5664],['Una escuela recicla 38 kg al mes. ¿Cuántos kg en 9 meses?',342],['Un museo recibe 1176 visitantes por semana. ¿Cuántos en 5 semanas?',5880],['Una camiseta necesita 22 botellas. ¿Cuántas para 100 camisetas?',2200],['Hay 32 sacos de 25 kg. ¿Cuántos kg son?',800],['Una biblioteca tiene 125 libros en cada estantería y 8 estanterías. ¿Cuántos libros?',1000],['Una caja tiene 48 lápices. ¿Cuántos lápices hay en 25 cajas?',1200],['Una excursión tiene 7 autobuses con 54 alumnos cada uno. ¿Cuántos alumnos?',378]];
 foreach($probs as [$q,$a])$p[]=mc($q,$a,[$a+20,$a-20,$a+100]);
 // Written questions: intentionally broad and repeated concepts, but generated values vary.
 foreach([13,27,46,58,72,105,214,306] as $n)$p[]=wr("Escribe solo el resultado: $n × 10 = ?",$n*10,'Multiplicar por 10 añade un cero a un número entero.');
 foreach([[24,30],[36,20],[42,50],[17,40],[23,200],[14,300]] as [$a,$b])$p[]=wr("Escribe solo el resultado: $a × $b = ?",$a*$b,'Puedes multiplicar primero por la cifra sin ceros y después añadir los ceros.');
 foreach([[3,4],[5,3],[7,2],[8,2],[9,3],[6,2]] as [$b,$e])$p[]=wr("Escribe el valor de $b^$e = ?",$b**$e,'La potencia indica cuántas veces se multiplica la base por sí misma.');
 foreach([['5 × (6 + 4)',50],['30 − 4 × 5',10],['(9 + 3) × 4',48],['7 × 8 + 6',62],['50 − 6 × 7',8],['(20 − 8) × 3',36]] as [$q,$a])$p[]=wr("Resuelve y escribe el resultado: $q = ?",$a,'Primero paréntesis; después multiplicaciones; al final sumas y restas.');
 return $p;
}
$pool=pool();$mcPool=array_values(array_filter($pool,fn($q)=>$q['type']==='mc'));$writePool=array_values(array_filter($pool,fn($q)=>$q['type']==='write'));shuffle($mcPool);shuffle($writePool);$questions=array_merge(array_slice($mcPool,0,10),array_slice($writePool,0,10));shuffle($questions);
$submitted=$_SERVER['REQUEST_METHOD']==='POST';$results=[];$score=0;
if($submitted && isset($_POST['q'])){
 $questions=$_SESSION['math_exam_questions']??$questions;
 foreach($questions as $i=>$q){$given=trim((string)($_POST['q'][$i]??''));$expected=trim((string)$q['answer']);$norm=function($v){$v=mb_strtolower(trim((string)$v),'UTF-8');$v=str_replace([',','.','€',' '],'',$v);return $v;};$correct=$norm($given)===$norm($expected);if($correct)$score++;$results[$i]=['given'=>$given,'correct'=>$correct];}
 $_SESSION['math_exam_last']=['score'=>$score,'total'=>count($questions)];
}
if(!$submitted) $_SESSION['math_exam_questions']=$questions;
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#2f8fe5"><title>Examen general de Matemáticas · Academia Star</title><link rel="stylesheet" href="assets/nuevo_curso/app.css?v=625"><style>
:root{--blue:#2f8fe5;--violet:#7558e8;--ink:#25243a;--muted:#77758c;--line:#ebe8f5;--shadow:0 14px 35px rgba(45,35,95,.08)}.course-only .sidebar{display:flex}.course-only .main{margin-left:260px}.exam-hero{background:linear-gradient(135deg,#236fc1,#7558e8);color:#fff;border-radius:28px;padding:27px;box-shadow:0 18px 40px rgba(45,60,160,.18)}.exam-hero h2{margin:7px 0;font-size:30px}.exam-hero p{margin:0;opacity:.92}.exam-meta{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px}.chip{padding:7px 10px;border-radius:999px;background:rgba(255,255,255,.15);font-size:12px;font-weight:900}.questions{display:grid;gap:14px;margin-top:20px}.qcard{background:#fff;border:1px solid var(--line);border-radius:20px;padding:20px;box-shadow:var(--shadow)}.qnum{display:inline-grid;place-items:center;width:34px;height:34px;border-radius:11px;background:#eef5ff;color:#286ab2;font-weight:900}.qcard h3{margin:12px 0 15px;font-size:18px;line-height:1.4}.opts{display:grid;gap:9px}.opt{display:block;border:1px solid var(--line);padding:12px 13px;border-radius:13px;cursor:pointer;font-weight:800}.opt input{margin-right:9px}.write{width:100%;box-sizing:border-box;border:1px solid #dcd9e9;border-radius:13px;padding:13px;font-size:17px}.submit{margin-top:18px}.result{margin-top:20px;background:#fff;border:1px solid var(--line);border-radius:24px;padding:24px;text-align:center}.score{font-size:42px;font-weight:950;color:#2f8fe5}.wrong{border-color:#f0c6c6}.ok{border-color:#bfe5ce}.correction{margin-top:9px;color:#6b657d}.new{display:inline-block;margin-top:15px;padding:12px 16px;border-radius:13px;background:linear-gradient(135deg,#7558e8,#a15de8);color:#fff;text-decoration:none;font-weight:900}@media(max-width:760px){.course-only .main{margin-left:0}.course-only .sidebar{transform:translateX(-100%)}.course-only .sidebar.open{transform:translateX(0)}.exam-hero{padding:22px}.exam-hero h2{font-size:25px}}
</style></head><body class="course-only"><div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">L</div><div><strong>Academia</strong><span>Nuevo curso</span></div></div><nav><a class="nav-btn" href="nuevo_curso.php"><span>🏠</span> Inicio</a><a class="nav-btn" href="asignatura.php?subject=lengua"><span>📖</span> Lengua</a><a class="nav-btn active" href="asignatura.php?subject=matematicas"><span>🔢</span> Matemáticas</a><a class="nav-btn" href="tasks.php"><span>📝</span> Tareas</a><a class="nav-btn" href="profile.php"><span>👧</span> Perfil</a></nav><a class="parent-btn" href="nuevo_curso.php">⌂ Nuevo curso</a><?php if(($user['role']??'')==='admin'): ?><a class="parent-btn" href="../admin/panel.php">🔒 Panel de Juanra</a><?php endif; ?></aside><main class="main"><header class="topbar"><button class="menu-btn" id="menuBtn" type="button">☰</button><div class="greeting"><span class="eyebrow">MATEMÁTICAS · EXAMEN</span><h1>📝 Examen general</h1></div><div class="stats-mini"><span>🔥 <b><?= (int)$profile['daily_streak'] ?></b></span><span>⭐ <b><?= (int)$profile['xp'] ?></b></span></div></header>
<section class="exam-hero"><span class="eyebrow" style="color:#fff">20 PREGUNTAS</span><h2>Examen general del tema</h2><p>Incluye todos los contenidos trabajados. Cada intento cambia las preguntas y su orden.</p><div class="exam-meta"><span class="chip">10 de elegir</span><span class="chip">10 de escribir</span><span class="chip">Multiplicaciones</span><span class="chip">Potencias</span><span class="chip">Problemas</span></div></section>
<?php if($submitted): ?><section class="result"><h2>Resultado</h2><div class="score"><?= $score ?>/<?= count($questions) ?></div><p><?= $score>=18?'Muy bien. Sigue repasando para llegar seguro al examen.':($score>=14?'Buen trabajo, pero todavía hay cosas que reforzar.':'Hay que repetir el bloque y volver a intentarlo.') ?></p><a class="new" href="matematicas_examen.php?nuevo=<?= time() ?>">🔄 Hacer otro examen diferente</a></section><?php endif; ?>
<form method="post" class="questions"><?php foreach($questions as $i=>$q): $res=$results[$i]??null; ?><section class="qcard <?= $res?($res['correct']?'ok':'wrong'):'' ?>"><span class="qnum"><?= $i+1 ?></span><h3><?= e($q['prompt']) ?></h3><?php if($submitted): ?><p><b>Tu respuesta:</b> <?= e($res['given']??'') ?></p><?php if(!$res['correct']): ?><p class="correction"><b>Correcta:</b> <?= e($q['answer']) ?><?php if(!empty($q['explain'])): ?> · <?= e($q['explain']) ?><?php endif; ?></p><?php endif; ?><?php else: ?><?php if($q['type']==='mc'): ?><div class="opts"><?php foreach($q['options'] as $o): ?><label class="opt"><input type="radio" name="q[<?= $i ?>]" value="<?= e($o) ?>" required> <?= e($o) ?></label><?php endforeach; ?></div><?php else: ?><input class="write" name="q[<?= $i ?>]" type="text" inputmode="numeric" autocomplete="off" placeholder="Escribe el resultado" required><?php endif; ?><?php endif; ?></section><?php endforeach; ?><?php if(!$submitted): ?><button class="btn submit" type="submit">Comprobar examen</button><?php endif; ?></form>
</main></div><script>const m=document.getElementById('menuBtn'),s=document.querySelector('.sidebar');if(m)m.onclick=()=>s.classList.toggle('open');</script></body></html>
