<?php
require_once __DIR__ . '/../app/auth.php';
require_once __DIR__ . '/../app/helpers.php';
$user=require_login();$profile=ensure_student_profile((int)$user['id']);
$subjects=['lengua'=>['name'=>'Lengua','icon'=>'📖','color'=>'#7558e8'],'matematicas'=>['name'=>'Matemáticas','icon'=>'🔢','color'=>'#2f8fe5']];
$subject=$_GET['subject']??'';$topic=$_GET['topic']??'';
if(!isset($subjects[$subject])||$topic===''){header('Location: nuevo_curso.php');exit;}$s=$subjects[$subject];$tasks=[];
try{$db=db();$q=$db->prepare("SELECT id,title,topic_key,description,duration_minutes,xp FROM study_tasks WHERE active=1 AND subject_key=? AND topic_key=? ORDER BY id ASC");$q->execute([$subject,$topic]);$tasks=$q->fetchAll();}catch(Throwable $e){$tasks=[];}
if(!$tasks){header('Location: asignatura.php?subject='.urlencode($subject));exit;}$topicTitle=$tasks[0]['title'];$total=count($tasks);
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#7558e8"><title>Tema · <?= e($topicTitle) ?> · Academia Star</title><link rel="stylesheet" href="assets/nuevo_curso/app.css?v=619a"><style>
:root{--ink:#25243a;--muted:#77758c;--line:#ebe8f5;--shadow:0 14px 35px rgba(45,35,95,.08)}.course-only .sidebar{display:flex}.course-only .main{margin-left:260px}.crumbs{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:22px 0 15px;font-size:13px}.crumbs a{color:#6a64a0;text-decoration:none;font-weight:800}.topic-head{background:linear-gradient(135deg,<?= e($s['color']) ?>,#a15de8);color:#fff;border-radius:28px;padding:30px;box-shadow:0 18px 40px rgba(60,40,150,.16)}.topic-kicker{font-size:12px;font-weight:900;letter-spacing:.08em;opacity:.85}.topic-head h2{margin:8px 0 5px;font-size:30px}.topic-head p{margin:0;opacity:.9}.content-list{display:grid;gap:15px;margin-top:22px}.content-card{background:#fff;border:1px solid var(--line);border-radius:22px;padding:20px;box-shadow:var(--shadow);display:flex;align-items:center;justify-content:space-between;gap:18px}.content-main{display:flex;align-items:flex-start;gap:14px}.content-num{width:42px;height:42px;border-radius:13px;background:#f0edff;color:<?= e($s['color']) ?>;display:grid;place-items:center;font-weight:900;flex:none}.content-card h3{margin:0;font-size:18px}.lesson-structure{display:grid;grid-template-columns:1fr;gap:12px;margin-top:18px}.lesson-structure article{border-radius:16px;padding:16px;border:1px solid #dbeafe;background:#f8fbff}.lesson-structure .question-box{border-left:5px solid #2563eb;background:#eff6ff}.lesson-structure .answer-box{border-left:5px solid #16a34a;background:#f0fdf4}.lesson-structure .explain-box{border-left:5px solid #9333ea;background:#faf5ff}.lesson-structure strong{display:block;margin-bottom:6px}.lesson-structure p{margin:0;line-height:1.6;color:#334155}.content-card p{margin:5px 0 0;color:var(--muted);font-size:13px}.content-meta{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.tag{display:inline-flex;padding:6px 9px;border-radius:999px;background:#f4f1fb;color:#5d5872;font-size:11px;font-weight:800}.actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.actions a{text-decoration:none;padding:10px 12px;border-radius:11px;background:#f3f1fa;color:#3d3852;font-size:12px;font-weight:900;white-space:nowrap}.actions a.primary{background:linear-gradient(135deg,<?= e($s['color']) ?>,#a15de8);color:#fff}.bottom-back{display:inline-block;margin-top:20px;text-decoration:none;color:#5d5872;font-weight:800}@media(max-width:760px){.course-only .main{margin-left:0}.course-only .sidebar{transform:translateX(-100%)}.course-only .sidebar.open{transform:translateX(0)}.content-card{align-items:flex-start;flex-direction:column}.actions{width:100%;justify-content:stretch}.actions a{flex:1;text-align:center}.topic-head{padding:24px}.topic-head h2{font-size:25px}}
</style></head><body class="course-only"><div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">L</div><div><strong>Academia</strong><span>Nuevo curso</span></div></div><nav><a class="nav-btn" href="nuevo_curso.php"><span>🏠</span> Inicio</a><a class="nav-btn <?= $subject==='lengua'?'active':'' ?>" href="asignatura.php?subject=lengua"><span>📖</span> Lengua</a><a class="nav-btn <?= $subject==='matematicas'?'active':'' ?>" href="asignatura.php?subject=matematicas"><span>🔢</span> Matemáticas</a><a class="nav-btn" href="tasks.php"><span>📝</span> Tareas</a><a class="nav-btn" href="profile.php"><span>👧</span> Perfil</a></nav><a class="parent-btn" href="nuevo_curso.php">⌂ Nuevo curso</a><?php if(($user['role']??'')==='admin'): ?><a class="parent-btn" href="../admin/panel.php">🔒 Panel de Juanra</a><?php endif; ?></aside>
<main class="main"><header class="topbar"><button class="menu-btn" id="menuBtn" type="button">☰</button><div class="greeting"><span class="eyebrow">CURSO 2026/27 · <?= e(strtoupper($s['name'])) ?></span><h1><?= e($s['icon']) ?> Tema</h1></div><div class="stats-mini"><span>🔥 <b><?= (int)$profile['daily_streak'] ?></b></span><span>⭐ <b><?= (int)$profile['xp'] ?></b></span></div></header>
<div class="crumbs"><a href="nuevo_curso.php">Nuevo curso</a><span>›</span><a href="asignatura.php?subject=<?= e($subject) ?>"><?= e($s['name']) ?></a><span>›</span><strong><?= e($topicTitle) ?></strong></div>
<section class="topic-head"><div class="topic-kicker">TEMA · <?= $total===1?'1':'CONTENIDOS' ?></div><h2><?= e($topicTitle) ?></h2><p>Todo lo que pertenece a este tema está reunido aquí. Primero puedes leerlo y después practicar y repasar.</p></section>
<?php if($subject==='matematicas'): ?><section class="lesson-structure"><article class="question-box"><strong>🔵 ¿Qué tienes que aprender?</strong><p>Lee el título y la pregunta del ejercicio. Identifica qué te piden antes de hacer ninguna operación.</p></article><article class="answer-box"><strong>🟢 Respuesta correcta</strong><p>Entra en «Leer tema» para ver las soluciones de los ejemplos y comprobar el resultado.</p></article><article class="explain-box"><strong>🟣 Explicación del procedimiento</strong><p>En «Estudiar» encontrarás pistas paso a paso. En «Practicar» tendrás que resolver por tu cuenta y en «Repasar» comprobarás lo que recuerdas.</p></article></section><?php endif; ?>
<div class="content-list"><?php foreach($tasks as $i=>$task): ?><article class="content-card"><div class="content-main"><div class="content-num"><?= $i+1 ?></div><div><h3><?= e($task['title']) ?></h3><p><?= e($task['description']) ?></p><div class="content-meta"><span class="tag">⏱ <?= (int)$task['duration_minutes'] ?> min</span><span class="tag">⭐ +<?= (int)$task['xp'] ?> XP</span></div></div></div><div class="actions"><a class="primary" href="task_activity.php?task_id=<?= (int)$task['id'] ?>&mode=read">📖 Leer tema</a><a href="task_activity.php?task_id=<?= (int)$task['id'] ?>&mode=study">🧠 Estudiar</a><a href="task_activity.php?task_id=<?= (int)$task['id'] ?>&mode=practice">✏️ Practicar</a><a href="task_activity.php?task_id=<?= (int)$task['id'] ?>&mode=review">🎯 Repasar</a></div></article><?php endforeach; ?></div>
<a class="bottom-back" href="asignatura.php?subject=<?= e($subject) ?>">← Volver a <?= e($s['name']) ?></a>
</main></div><script>const m=document.getElementById('menuBtn'),sbar=document.querySelector('.sidebar');if(m)m.onclick=()=>sbar.classList.toggle('open');document.querySelectorAll('.sidebar a').forEach(x=>x.addEventListener('click',()=>sbar.classList.remove('open')));</script></body></html>
