<?php
require_once __DIR__ . '/../app/auth.php';
require_once __DIR__ . '/../app/helpers.php';
$user = require_admin();
ensure_v44_tables();
ensure_student_money_tables();
$db = db();
$message = '';

$leireUser = $db->query("SELECT id,name,username FROM users WHERE username='leire' LIMIT 1")->fetch();
$leireId = $leireUser ? (int)$leireUser['id'] : 0;
if ($leireId) ensure_student_profile($leireId);

if ($_SERVER['REQUEST_METHOD'] === 'POST' && $leireId) {
    $action = $_POST['action'] ?? '';
    if ($action === 'adjust_money') {
        $amount = parse_money_to_cents((string)($_POST['amount'] ?? '0'));
        $direction = $_POST['direction'] ?? 'deposit';
        $reason = trim((string)($_POST['reason'] ?? 'Ajuste manual de Juanra')) ?: 'Ajuste manual de Juanra';
        if ($direction === 'withdraw') $amount = -abs($amount); else $amount = abs($amount);
        $message = wallet_adjust_balance($leireId, $amount, $reason, (int)$user['id'], $direction === 'withdraw' ? 'admin_withdraw' : 'admin_deposit')
            ? 'Saldo actualizado correctamente.'
            : 'No se pudo actualizar el saldo. Revisa la cantidad o el saldo disponible.';
    } elseif ($action === 'withdrawal_action') {
        $message = handle_withdrawal_admin_action((int)($_POST['request_id'] ?? 0), (string)($_POST['request_action'] ?? ''), (int)$user['id'], (string)($_POST['admin_note'] ?? ''));
    } elseif ($action === 'save_reward_rule') {
        $ruleId = (int)($_POST['rule_id'] ?? 0);
        $ruleMode = (string)($_POST['rule_mode'] ?? 'examen');
        $minScore = (float)str_replace(',', '.', (string)($_POST['min_score'] ?? '10'));
        $amountCents = (int)($_POST['amount_cents'] ?? 0);
        $active = !empty($_POST['active']);
        $message = save_reward_rule($ruleId, $ruleMode, $minScore, $amountCents, $active);
    } elseif ($action === 'avatar_upload' && isset($_FILES['avatar'])) {
        $message = save_profile_avatar_upload($leireId, $_FILES['avatar']);
    } elseif ($action === 'subject_done' || $action === 'subject_clear') {
        set_subject_official_exam_done($leireId, (string)($_POST['subject'] ?? ''), $action === 'subject_done', (string)($_POST['note'] ?? ''));
        $message = $action === 'subject_done' ? 'Asignatura marcada como examen oficial hecho.' : 'Asignatura reactivada para recomendaciones.';
    } elseif ($action === 'topic_done' || $action === 'topic_clear') {
        set_topic_official_exam_done($leireId, (int)($_POST['topic_id'] ?? 0), $action === 'topic_done', (string)($_POST['note'] ?? ''));
        $message = $action === 'topic_done' ? 'Tema marcado como examen oficial hecho.' : 'Tema reactivado para recomendaciones.';
    }
}

$topics = $db->query('SELECT t.*, COUNT(DISTINCT q.id) questions, COUNT(DISTINCT f.id) files FROM topics t LEFT JOIN questions q ON q.topic_id=t.id LEFT JOIN topic_files f ON f.topic_id=t.id GROUP BY t.id ORDER BY FIELD(t.subject,"Matemáticas","Lengua","Conocimiento del Medio","Inglés"), t.id ASC')->fetchAll();
$results = $db->query('SELECT r.*, u.name user_name, t.title topic_title, t.subject FROM results r JOIN users u ON u.id=r.user_id JOIN topics t ON t.id=r.topic_id ORDER BY r.created_at DESC LIMIT 12')->fetchAll();
$stat = $db->query('SELECT COUNT(*) total_results, ROUND(AVG(score),2) avg_score, SUM(correct_questions) corrects, SUM(total_questions-correct_questions) errors FROM results')->fetch() ?: [];
$bySubject = $db->query('SELECT t.subject, ROUND(AVG(r.score),2) avg_score, COUNT(r.id) tries FROM topics t LEFT JOIN results r ON r.topic_id=t.id GROUP BY t.subject ORDER BY FIELD(t.subject,"Matemáticas","Lengua","Conocimiento del Medio","Inglés")')->fetchAll();
$subjects = ['Matemáticas','Lengua','Conocimiento del Medio','Inglés'];
$leireProfile = $leireId ? ensure_student_profile($leireId) : null;
$xpHistory = $leireId ? $db->query('SELECT * FROM xp_history WHERE user_id='.$leireId.' ORDER BY created_at DESC LIMIT 10')->fetchAll() : [];
$walletHistory = $leireId ? wallet_transactions_for_user($leireId, 12) : [];
$withdrawals = withdrawal_requests_for_admin(30);
$rewardRules = reward_rules_for_admin();
$frequent = $leireId ? frequent_error_topics($leireId, 8) : [];
$weekly = $leireId ? weekly_summary_for_user($leireId) : ['total'=>0,'avg_score'=>0,'corrects'=>0,'errors'=>0,'best'=>null,'weak'=>null];
$tasks = $leireId ? ensure_daily_tasks($leireId) : [];
$shopCount = $leireId ? count(array_filter(shop_items_for_user($leireId), fn($i) => !empty($i['owned_id']))) : 0;
$subjectDone = $leireId ? subject_official_done_map($leireId) : [];
$topicDone = $leireId ? topic_official_done_map($leireId, array_map(fn($t)=>(int)$t['id'], $topics)) : [];
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Panel Juanra</title><link rel="stylesheet" href="../public/assets/css/style.css?v=5.15"><style>.admin-dashboard-hero{background:linear-gradient(135deg,rgba(25,18,70,.96),rgba(11,12,42,.96));border:1px solid rgba(132,92,255,.28);padding:24px;border-radius:22px}.admin-dashboard-hero h1{margin:.25rem 0 0;font-size:clamp(1.7rem,3vw,2.5rem);letter-spacing:-.04em}.eyebrow{font-size:.68rem;letter-spacing:.18em;color:#a996ff;font-weight:800}.admin-quick-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:22px}.admin-quick{display:flex;align-items:center;gap:10px;padding:14px;border-radius:15px;color:#fff;text-decoration:none;border:1px solid rgba(255,255,255,.1);min-width:0}.admin-quick b{width:38px;height:38px;border-radius:11px;display:grid;place-items:center;background:rgba(255,255,255,.16);font-size:1.25rem}.admin-quick span{display:grid;gap:2px;min-width:0}.admin-quick strong{font-size:.78rem}.admin-quick small{font-size:.65rem;opacity:.72}.admin-quick em{margin-left:auto;font-size:1.4rem;font-style:normal}.admin-quick.purple{background:linear-gradient(135deg,#5d2be8,#9d3df2)}.admin-quick.green{background:linear-gradient(135deg,#087c69,#0c9e8c)}.admin-quick.blue{background:linear-gradient(135deg,#0757b8,#176ee5)}.admin-quick.orange{background:linear-gradient(135deg,#a64b18,#d47722)}@media(max-width:800px){.admin-quick-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:480px){.admin-quick-grid{grid-template-columns:1fr}}</style></head><body><div class="wrap">
<header class="topbar"><div class="brand">⚙️ Panel de Juanra <span class="pill">V5.15</span></div><nav class="nav"><a class="secondary" href="../public/dashboard.php">App Leire</a><a class="secondary" href="../public/wallet.php">Dinero</a><a class="secondary" href="../public/profile.php">Perfil</a><a class="secondary" href="../public/trainer.php">Entrenador</a><a class="secondary" href="../public/shop.php">Tienda</a><a class="secondary" href="scans.php">Escaneos</a><a class="secondary" href="dazn.php">📺 Cuentas DAZN</a><a class="secondary" href="ai_settings.php">IA</a><a class="secondary" href="../public/logout.php">Salir</a></nav></header>
<section class="card admin-dashboard-hero"><div><span class="eyebrow">ACADEMIA STAR</span><h1>Bienvenido, Juanra <span aria-hidden="true">👋</span></h1><p class="muted">Panel de administración</p></div><div class="admin-quick-grid"><a class="admin-quick purple" href="dazn.php"><b>▣</b><span><strong>Cuentas</strong><small>Gestionar servicios</small></span><em>›</em></a><a class="admin-quick green" href="dazn.php#editor"><b>＋</b><span><strong>Nueva cuenta</strong><small>Añadir cuenta</small></span><em>›</em></a><a class="admin-quick blue" href="quick_exam.php"><b>▥</b><span><strong>Examen rápido</strong><small>Crear actividad</small></span><em>›</em></a><a class="admin-quick orange" href="scans.php"><b>▤</b><span><strong>Escaneos</strong><small>Ver documentos</small></span><em>›</em></a></div><?php if($message): ?><div class="notice reward"><?= e($message) ?></div><?php endif; ?></section>

<?php if($leireProfile): ?>
<section class="kid-hero admin-hero"><div class="avatar-card"><img class="avatar" src="../public/<?= e($leireProfile['avatar']) ?>" alt="Avatar Leire"><div class="level-badge">Nivel <?= (int)$leireProfile['level'] ?></div><div class="xpbar"><span style="width:<?= progress_percent($leireProfile) ?>%"></span></div><p class="muted">XP <?= (int)$leireProfile['xp'] ?>/<?= xp_for_next_level((int)$leireProfile['level']) ?></p></div><div class="card hero-main"><h2>Perfil de Leire</h2><div class="stats compact"><div class="mini"><b>💶 <?= e(format_cents((int)$leireProfile['coins'])) ?></b><span>Saldo actual</span></div><div class="mini"><b>🔥 <?= (int)$leireProfile['daily_streak'] ?></b><span>Racha diaria</span></div><div class="mini"><b><?= (int)$leireProfile['weekly_goal'] ?></b><span>Objetivo semanal</span></div><div class="mini"><b><?= (int)$shopCount ?></b><span>Recompensas compradas</span></div></div><form class="form compact-form" method="post" enctype="multipart/form-data"><input type="hidden" name="action" value="avatar_upload"><label><b>Cambiar foto de perfil</b><input class="input" type="file" name="avatar" accept="image/*" required></label><button class="btn secondary">Actualizar foto</button></form></div></section>
<?php endif; ?>

<section class="split"><div class="card"><h2>💶 Ingresar o retirar saldo</h2><p class="muted">El saldo está en céntimos/euros. Por ejemplo: 0,05 € = 5 céntimos.</p><form class="form" method="post"><input type="hidden" name="action" value="adjust_money"><select name="direction" class="input"><option value="deposit">Ingresar</option><option value="withdraw">Retirar</option></select><input class="input" name="amount" placeholder="Cantidad, ejemplo 0,05" required><input class="input" name="reason" placeholder="Motivo, ejemplo paga semanal / retirada en efectivo"><button class="btn">Aplicar ajuste</button></form></div><div class="card"><h2>📨 Solicitudes de retirada</h2><?php if(!$withdrawals): ?><p class="muted">No hay solicitudes todavía.</p><?php else: ?><div class="request-list"><?php foreach($withdrawals as $wr): ?><div class="subject request-card <?= e($wr['status']) ?>"><strong><?= e($wr['user_name']) ?> pide <?= e(format_cents((int)$wr['amount_cents'])) ?></strong><span class="muted"><?= e($wr['created_at']) ?> · Estado: <?= e($wr['status']) ?></span><?php if($wr['note']): ?><p><?= e($wr['note']) ?></p><?php endif; ?><?php if($wr['status']==='pending'): ?><form method="post" class="inline-form"><input type="hidden" name="action" value="withdrawal_action"><input type="hidden" name="request_id" value="<?= (int)$wr['id'] ?>"><input type="hidden" name="request_action" value="pay"><button class="btn small">Pagar y descontar</button></form><form method="post" class="inline-form"><input type="hidden" name="action" value="withdrawal_action"><input type="hidden" name="request_id" value="<?= (int)$wr['id'] ?>"><input type="hidden" name="request_action" value="reject"><button class="btn secondary small">Rechazar</button></form><?php endif; ?></div><?php endforeach; ?></div><?php endif; ?></div></section>

<section class="card"><h2>💶 Reglas de recompensa por nota</h2><p class="muted">Puedes cambiar qué nota necesita Leire y cuántos céntimos gana. La app usa la regla activa más alta que cumpla la nota. Ejemplo: en examen, nota 10 = 5 céntimos y nota 8 = 2 céntimos.</p><?php if(!$rewardRules): ?><p class="muted">No hay reglas todavía.</p><?php else: ?><div class="grid small"><?php foreach($rewardRules as $rule): ?><form method="post" class="subject"><input type="hidden" name="action" value="save_reward_rule"><input type="hidden" name="rule_id" value="<?= (int)$rule['id'] ?>"><strong>Regla #<?= (int)$rule['id'] ?></strong><label>Actividad<select class="input" name="rule_mode"><option value="examen" <?= $rule['mode']==='examen'?'selected':'' ?>>Examen</option><option value="deberes" <?= $rule['mode']==='deberes'?'selected':'' ?>>Deberes</option><option value="repaso" <?= $rule['mode']==='repaso'?'selected':'' ?>>Repaso</option><option value="batalla" <?= $rule['mode']==='batalla'?'selected':'' ?>>Reto Emilia</option></select></label><label>Nota mínima<input class="input" name="min_score" value="<?= e((string)$rule['min_score']) ?>"></label><label>Importe en céntimos<input class="input" name="amount_cents" type="number" min="0" value="<?= (int)$rule['amount_cents'] ?>"></label><label><input type="checkbox" name="active" value="1" <?= (int)$rule['active']===1?'checked':'' ?>> Regla activa</label><button class="btn secondary small">Guardar regla</button></form><?php endforeach; ?></div><?php endif; ?><h3>Añadir nueva regla</h3><form class="form compact-form" method="post"><input type="hidden" name="action" value="save_reward_rule"><input type="hidden" name="rule_id" value="0"><select class="input" name="rule_mode"><option value="examen">Examen</option><option value="deberes">Deberes</option><option value="repaso">Repaso</option><option value="batalla">Reto Emilia</option></select><input class="input" name="min_score" placeholder="Nota mínima, ejemplo 9,5"><input class="input" name="amount_cents" type="number" min="0" placeholder="Importe en céntimos"><label><input type="checkbox" name="active" value="1" checked> Activa</label><button class="btn">Añadir regla</button></form></section>

<section class="card"><h2>🏫 Exámenes oficiales del colegio</h2><p class="muted">Cuando Leire ya haya hecho el examen oficial en el cole, márcalo aquí. Ese tema o asignatura deja de salir en el plan diario, retos y recomendaciones.</p><h3>Por asignatura</h3><div class="grid small"><?php foreach($subjects as $sub): $done=!empty($subjectDone[$sub]); ?><div class="subject <?= $done?'done':'' ?>"><strong><?= subject_icon($sub) ?> <?= e($sub) ?></strong><span class="muted"><?= $done?'Examen oficial hecho':'Activa para recomendar' ?></span><form method="post" class="inline-form"><input type="hidden" name="action" value="<?= $done?'subject_clear':'subject_done' ?>"><input type="hidden" name="subject" value="<?= e($sub) ?>"><button class="btn <?= $done?'secondary':'' ?> small"><?= $done?'Reactivar asignatura':'Marcar examen hecho' ?></button></form></div><?php endforeach; ?></div></section>

<section class="card"><h2>Biblioteca de temas</h2><table class="table"><tr><th>Asignatura</th><th>Tema</th><th>Preguntas</th><th>Estado colegio</th><th>Acciones</th></tr><?php foreach($topics as $t): $tdone=!empty($topicDone[(int)$t['id']]); ?><tr class="<?= $tdone?'done-row':'' ?>"><td><?= subject_icon($t['subject']) ?> <?= e($t['subject']) ?></td><td><?= e($t['title']) ?></td><td><?= (int)$t['questions'] ?></td><td><?= $tdone?'<span class="pill equipped">Examen hecho</span>':'<span class="pill">Activo</span>' ?></td><td><a href="topic_edit.php?id=<?= (int)$t['id'] ?>">Editar</a> · <a href="question_edit.php?topic_id=<?= (int)$t['id'] ?>">Pregunta</a> · <a href="uploads.php?topic_id=<?= (int)$t['id'] ?>">Subir</a> · <a href="print_exam.php?topic_id=<?= (int)$t['id'] ?>" target="_blank">Imprimir</a><form method="post" class="inline-form"><input type="hidden" name="action" value="<?= $tdone?'topic_clear':'topic_done' ?>"><input type="hidden" name="topic_id" value="<?= (int)$t['id'] ?>"><button class="btn secondary small"><?= $tdone?'Reactivar':'Examen colegio hecho' ?></button></form></td></tr><?php endforeach; ?></table></section>

<section class="card"><h2>🧠 Resumen semanal inteligente</h2><div class="stats compact"><div class="mini"><b><?= (int)$weekly['total'] ?></b><span>Actividades esta semana</span></div><div class="mini"><b><?= e((string)$weekly['avg_score']) ?>/10</b><span>Media semanal</span></div><div class="mini"><b><?= (int)$weekly['corrects'] ?></b><span>Aciertos</span></div><div class="mini"><b><?= (int)$weekly['errors'] ?></b><span>Fallos</span></div></div><div class="notice"><b>Recomendación:</b> <?= $leireId ? e(trainer_message($leireId)) : 'Aún no hay usuario Leire.' ?></div></section>
<section class="card"><h2>✅ Plan diario de Leire</h2><?php if(!$tasks): ?><p class="muted">No hay plan generado todavía.</p><?php else: ?><div class="grid small"><?php foreach($tasks as $task): ?><div class="subject <?= !empty($task['completed'])?'done':'' ?>"><strong><?= !empty($task['completed'])?'✅':'🎯' ?> <?= e($task['title']) ?></strong><span class="muted"><?= e($task['subject'] ?: 'General') ?> · +<?= (int)$task['xp_reward'] ?> XP</span></div><?php endforeach; ?></div><?php endif; ?></section>
<div class="stats"><div class="mini"><b><?= (int)($stat['total_results'] ?? 0) ?></b><span>Pruebas hechas</span></div><div class="mini"><b><?= !empty($stat['avg_score']) ? e((string)$stat['avg_score']).'/10' : '-' ?></b><span>Nota media</span></div><div class="mini"><b><?= (int)($stat['corrects'] ?? 0) ?></b><span>Aciertos</span></div><div class="mini"><b><?= (int)($stat['errors'] ?? 0) ?></b><span>Errores</span></div></div>
<section class="split"><div class="card"><h2>💶 Movimientos recientes</h2><?php if(!$walletHistory): ?><p class="muted">Sin movimientos manuales todavía.</p><?php else: ?><table class="table"><tr><th>Fecha</th><th>Motivo</th><th>Cantidad</th></tr><?php foreach($walletHistory as $w): ?><tr><td><?= e($w['created_at']) ?></td><td><?= e($w['reason']) ?></td><td><b><?= e(format_signed_cents((int)$w['amount_cents'])) ?></b></td></tr><?php endforeach; ?></table><?php endif; ?></div><div class="card"><h2>Últimas recompensas</h2><?php if(!$xpHistory): ?><p class="muted">Sin recompensas todavía.</p><?php else: ?><table class="table"><tr><th>Fecha</th><th>Motivo</th><th>XP</th><th>€</th></tr><?php foreach($xpHistory as $x): ?><tr><td><?= e($x['created_at']) ?></td><td><?= e($x['reason']) ?></td><td>+<?= (int)$x['xp'] ?></td><td><?= e(reward_text((int)$x['coins'])) ?></td></tr><?php endforeach; ?></table><?php endif; ?></div></section>
<section class="card"><h2>Resumen por asignatura</h2><table class="table"><tr><th>Asignatura</th><th>Intentos</th><th>Media</th><th>Nivel</th></tr><?php foreach($bySubject as $s): ?><tr><td><?= subject_icon($s['subject']) ?> <?= e($s['subject']) ?></td><td><?= (int)$s['tries'] ?></td><td><?= $s['avg_score'] ? e((string)$s['avg_score']).'/10' : '-' ?></td><td><span class="pill"><?= e(level_from_score($s['avg_score'] !== null ? (float)$s['avg_score'] : null)) ?></span></td></tr><?php endforeach; ?></table></section>
<?php if($frequent): ?><section class="card"><h2>Errores frecuentes detectados</h2><table class="table"><tr><th>Tema</th><th>Fallos</th><th>Acción</th></tr><?php foreach($frequent as $er): ?><tr><td><?= e($er['subject'].' · '.$er['title']) ?></td><td><b><?= (int)$er['errors'] ?></b></td><td><a href="../public/exam.php?topic_id=<?= (int)$er['topic_id'] ?>&mode=repaso">Crear repaso</a> · <a href="../public/exam.php?topic_id=<?= (int)$er['topic_id'] ?>&mode=batalla">Reto</a></td></tr><?php endforeach; ?></table></section><?php endif; ?>
<section class="card"><h2>Últimos resultados de Leire</h2><?php if(!$results): ?><p class="muted">Sin resultados todavía.</p><?php else: ?><table class="table"><tr><th>Fecha</th><th>Alumno</th><th>Tema</th><th>Modo</th><th>Nota</th></tr><?php foreach($results as $r): ?><tr><td><?= e($r['created_at']) ?></td><td><?= e($r['user_name']) ?></td><td><?= e($r['subject'].' - '.$r['topic_title']) ?></td><td><?= e($r['mode']) ?></td><td><b><?= e((string)$r['score']) ?>/10</b></td></tr><?php endforeach; ?></table><?php endif; ?></section>
</div></body></html>
